//===- DerivLabDialect.h - DerivLab Dialect Definition ---------*- C++ -*-===//
//
//  This file declares the DerivLab MLIR dialect.
//===----------------------------------------------------------------------===//

#ifndef DERIVLAB_DERIVLABDIALECT_H
#define DERIVLAB_DERIVLABDIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

namespace mlir {
namespace derivlab {

class DerivLabDialect : public Dialect {
public:
  explicit DerivLabDialect(MLIRContext *context);
  static StringRef getDialectNamespace() { return "derivlab"; }
};

// Forward declare operation classes (generated by TableGen in real use)
class SimulateGBMOp;
class PayoffOp;

} // end namespace derivlab
} // end namespace mlir

#endif // DERIVLAB_DERIVLABDIALECT_H
