
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ADITI/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0/LocalCache/local-packages/Python313/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:46 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
