name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Configure CMake
        run: |
          cmake -S mlir -B build
      - name: Build
        run: |
          cmake --build build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure test script is executable
        run: chmod +x scripts/test_pipeline.sh
      - name: Run integration tests
        run: bash scripts/test_pipeline.sh
